version: '3.9'
services:
  api:
    build: ./backend/
    ports:
      - 3000:3000
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:?"SECRET_KEY_BASE is required"}
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - PORT=${API_PORT:-3000}
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - PRODUCTION_DATABASE_USRENAME=${DATABASE_USRENAME:?"DATABASE_USRENAME is required"}
      - PRODUCTION_DATABASE_PASSWORD=${DATABASE_PASSWORD:?"DATABASE_PASSWORD is required"}
      - PRODUCTION_DATABASE_NAME=${DATABASE_NAME:-database}
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:?"DATABASE_PASSWORD is required"}
      - POSTGRES_USER-${DATABASE_USRENAME:-postgres}
      - PRODUCTION_DATABASE_NAME=${DATABASE_NAME:-database}
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
